### PR TITLE
chore: sync build flags with upstream

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Lctrs** [comment]
@gasinvein any idea how we could integrate the vkd3d-d3d12 changes made in https://github.com/GloriousEggroll/proton-ge-custom/commit/d9452ec4b5ebb42ee75a60337397b479462f8be6 or if it is needed at all ?

**Comment by Lctrs** [comment]
bot, build

**Comment by gasinvein** [comment]
@Lctrs I don't closely follow Proton internals anymore. What exactly are the changes and what's the problem with them you want to solve?

**Comment by Lctrs** [comment]
They now seem to build the d3d12 part of vkd3d before wine as a new dependency. I don't know what for and it builds fine in our case without it but I don't know what are the implications of not building wine without it.

**Comment by Lctrs** [comment]
I'm merging this now as we have the annoying wine-mono popup but I would like to continue the discussion on this.

**Comment by gasinvein** [comment]
Hmm, is it a GE-specific change?

**Comment by Lctrs** [comment]
No. I have found the corresponding commit in Proton and it's part of the latest experimental version (https://github.com/ValveSoftware/Proton/commit/4e268f856c8d52fe43f6d4387add2007e72b902b)

**Comment by gasinvein** [comment]
Ugh. So they just build native vkd3d now as a Wine dependency? I'm pretty sure it already used to be this way in the past.
In any case, building native vkd3d should be straightforward.

**Pull request merged**
