### PR TITLE
Fix build for 7.14-1

### PR DESCRIPTION
**Pull request by ColinKinloch**
Same changes as #88 on top of 7.14-1

### CODE REVIEW

**Comment by Lctrs** [comment]
Not very satisfied with adfko requirements being split in 2 different files again.

**Comment by ColinKinloch** [comment]
Oh, sorry I was just copying Proton-Exp.
I'll fix it.

**Comment by ColinKinloch** [comment]
Same issue with Elden Ring as #85

**Comment by ColinKinloch** [comment]
I've transposed `./files/lib64/wine/vkd3d-proton/d3d12.dll` between 7.9 and 7.10.
This causes the error in 7.9 and resolving it in 7.10.
The problem is somewhere here: https://github.com/HansKristian-Work/vkd3d-proton/compare/c411d0d0...6353050

**Comment by ColinKinloch** [comment]
Launching Elden Ring with `VKD3D_DEBUG=trace %command%` prints:
```
0194:info:vkd3d_init_device_caps: KHR_dynamic_rendering is not supported by this implementation. This is required for correct operation.
```
`vulkaninfo` shows `VK_KHR_dynamic_rendering` is present in host but is missing in the flatpak.

**Comment by ColinKinloch** [comment]
With mesa-git running Elden Ring prints:
```
01b4:err:vkd3d_init_device_caps: Null descriptor in VK_EXT_robustness2 is not supported by this implementation. This is required for correct operation.
```

**Comment by ColinKinloch** [comment]
I suppose it makes sense to wait for runtime support for mesa 22 https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1391

**Pull request merged**
