### PR TITLE
Update Proton-GE to 9.10

### PR DESCRIPTION
**Pull request by ChrisHobday**
Updates Proton-GE to 9.10, switch to using the Proton-GE archived releases instead of building all the modules from source, removes unneeded folders and files, and update ReadMe to better reflect the changes. Note: the many commits are progressively updating the missing versions.

### CODE REVIEW

**Comment by bbhtt** [comment]
Can you please squash the  `Update to Proton-GE $versio` commits? They don't need to be separate, it makes reviewing by commit a bit heard.

**Comment by ChrisHobday** [comment]
Alright https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/pull/190/commits/3729a457bd415605154733ddd35a1f08dd7c6c53 is the squashed version of all the commits.

**Comment by bbhtt** [comment]
Something is wrong, Github is preventing me from commenting on the PR. Probably the large squash confused it.

image

**Comment by bbhtt** [comment]
A few comments:

- Drop `appstream-compose: false` and running `appstream-compose` in build commands everywhere. THat is not needed anymore.
- Convert this to an `archive` source https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/pull/190/files#diff-70d9b2d31f6fe569a1f2841ad84120d4bf5b440e6b99c40ce1acf79e56b3a578R13 and drop the `tar -xf` step.
- Drop the various usages of `sed`, use a patch instead. sed is risky.
- Use `type: patch` for `toolmanifest.patch` and drop the `patch` command.

It seems you dropped most of wine and vulkan parts from the original manifest - why?

**Comment by ChrisHobday** [comment]
I'll remove the appsteam-compose lines.

I did have the release as an archive source and the toolmanifest.patch as a patch source originally, but was having trouble figuring out how to have it apply the toolmanifest.patch to the archive, and so resorted to making them both files and manually taring it first and using the patch command in the build-commands instead. I'll look into getting a patch source to apply to archives again.

The sed patch was also a compatibilitytool.patch file at first, but was not able to be applied between releases because the compatibilitytool.vdf file changes to include the release version with each update, so I'm not sure there is a better way than using the regex of sed so that the patch works between releases.

I believe everything needed is included in the archived release, and wine/vulkan are not needed separately. In my testing I was able to play Baldur's Gate 3 (Vulkan), Doom Eternal, and Resident Evil 2, all in conjunction with the Gamescope Flatpak and with HDR working.

**Comment by bbhtt** [comment]
> I did have the release as an archive source and the toolmanifest.patch as a patch source originally, but was having trouble figuring out how to have it apply the toolmanifest.patch to the archive, and so resorted to making them both files and manually taring it first and using the patch command in the build-commands instead. I'll look into getting a patch source to apply to archives again.

> The sed patch was also a compatibilitytool.patch file at first, but was not able to be applied between releases because the compatibilitytool.vdf file changes to include the release version with each update, so I'm not sure there is a better way than using the regex of sed so that the patch works between releases.

A patch would be best You can find the docs here if needed https://docs.flatpak.org/en/latest/module-sources.html

You likely need to modify the patch path marker on the top so that applies. It should be `./path/....`

**Comment by ChrisHobday** [comment]
I'll add the symlinks back.

Looking at the Proton-GE workflow build file https://github.com/GloriousEggroll/proton-ge-custom/blob/master/.github/workflows/build.yml , I do see a section that appears to be applying the proton-ge-custom patches and I think this is how the releases are being made.

**Comment by ChrisHobday** [comment]
I've made the requested changes, and retested the same Steam games with the flathubbot provided install.

**Comment by ChrisHobday** [comment]
I've been added as a maintainer. I'm going to leave this pull request up for another couple of days before merging it, to give anyone else interested a chance to test it out or request changes.

**Pull request merged**
