### PR TITLE
proton-ge: update to 6.5-GE-1-1

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build

**Comment by Lctrs** [comment]
@LeandroStanger why did you restarted it ? Previous build's log showed a real failure, so this one will without doubt fail again. I just don't have the time to take a look at it right now.

**Comment by gasinvein** [comment]
@Lctrs Probably this failure is due to updated steam_helper, it needs `libdl` now. Try cherry-picking this commit: flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-Exp@a9527a1398096f169f87c659d65f076c9013878e

**Comment by Lctrs** [comment]
Thank you @gasinvein, I must have missed it when translating upstream makefile.

**Comment by gasinvein** [comment]
`glslangValidator` in the SDK doesn't support flags that vkd3d-proton passes to it. I guess we would need to either bundle updated glslang or patch vkd3d.

**Pull request merged**
